const FETCH_GAMES = "FETCH_GAMES"
const FILTER_GAMES = "FILTER_GAMES"
const FETCH_DETAIL = "FETCH_DETAIL"
const FETCH_GENRES = "FETCH_GENRES"
const SET_PAGE = "SET_PAGE"

export { FETCH_GAMES, FILTER_GAMES, FETCH_DETAIL, FETCH_GENRES, SET_PAGE }
